force-app/main/default/objects/Car_Service__c/Car_Service__c.object-meta.xml
<CustomObject>
    <label>Car Service</label>
    <nameField>
        <label>Car Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Car Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Service__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Car</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Car Services</relationshipLabel>
    <relationshipName>Car_Services</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Service__c/fields/Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Service_Name__c</fullName>
    <label>Service Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarBrand__c.field-meta.xml
<CustomField>
    <fullName>CarBrand__c</fullName>
    <label>CarBrand</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarVinCode__c.field-meta.xml
<CustomField>
    <fullName>CarVinCode__c</fullName>
    <label>CarVinCode</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseService.cls
public with sharing class CaseService {

    public static void autoCreateCarService(Map<Id, Case> caseMap){

        if (caseMap == null || caseMap.isEmpty()) return;

        Set<String> vinCodes = new Set<String>();
        for (Case caseRecord : caseMap.values()) {
            if (caseRecord.CarVinCode__c != null && !String.isBlank(caseRecord.CarVinCode__c)) {
                vinCodes.add(caseRecord.CarVinCode__c);
            }
        }

        List<Product2> cars = [SELECT Id, Brand__c, Model__c, VIN_Number__c 
                                FROM Product2
                                WHERE VIN_Number__c IN :vinCodes ];

        if (cars == null || cars.isEmpty()) return;

        List<Car_Service__c> carServices = new List<Car_Service__c>();

        for(Case caseRecord  : caseMap.values()){
            if(caseRecord .CarVinCode__c !=null ){  // || caseRecord .CarVinCode__c.isEmpty()
                for(Product2 car : cars){
                    if(car.VIN_Number__c == caseRecord .CarVinCode__c){ // && car.Brand__c == caseRecord .CarBrand__c

                        Car_Service__c newCarService = new Car_Service__c();
                        newCarService.Name = caseRecord .Subject;
                        newCarService.Service_Name__c = caseRecord .Subject;
                        newCarService.Description__c = caseRecord .Description;
                        newCarService.Date__c = Date.today();
                        newCarService.Car__c = car.Id;
                        
                        carServices.add(newCarService);
                    } 
                    
                    
                }
            }
        }

        if(carServices.size() > 0){
            insert carServices;
        }

    }

}