force-app/main/default/objects/Planned_Sales__c/fields/Car_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Type__c</fullName>
    <label>Car Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlannedSalesService.cls
public with sharing class PlannedSalesService {

    public static void uniquePlannedSales(List<Planned_Sales__c> triggerNew){

        List<Planned_Sales__c> existingRecords  = [
        SELECT Id, Year__c, Month__c, Car_Type__c
        FROM Planned_Sales__c 
        ];

        for (Planned_Sales__c ps : triggerNew){
            for (Planned_Sales__c  existingRecord : existingRecords){
                if(existingRecord.Year__c == ps.Year__c &&
                   existingRecord.Month__c == ps.Month__c &&
                   existingRecord.Car_Type__c == ps.Car_Type__c &&
                   existingRecord.Id != ps.Id){

                     ps.addError('A Planned Sales record already exists for this Year, Month, and Car Type.');
                }
            }
        }
    }
}